name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Web SDK dependencies
      run: dotnet restore ./src/Example.Web.Sdk/Example.Web.Sdk.sln
    - name: Build Web SDK
      run: dotnet build --configuration Release --no-restore ./src/Example.Web.Sdk/Example.Web.Sdk.sln
    - name: Test Web SDK
      run: dotnet test --no-restore --verbosity normal ./src/Example.Web.Sdk/Example.Web.Sdk.sln
    - name: Install Web API dependencies
      run: dotnet restore ./src/Example.Web.Api/Example.Web.Api.sln
    - name: Build Web API
      run: dotnet build --configuration Release --no-restore ./src/Example.Web.Api/Example.Web.Api.sln
    - name: Test Web API
      run: dotnet test --no-restore --verbosity normal ./src/Example.Web.Api/Example.Web.Api.sln
